services:
  proxy:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
  auth:
    build: 
      context: auth
      dockerfile: Dockerfile
    environment:
      - SIGNING_KEY=supersecretkeysupersecretkeysupersecretkey 
      - ISSUER=http://localhost:8080
      - AUDIENCE=http://localhost:8080
      - DATABASE_URL=postgres://root:root@postgresql:5432/user_db
  postgresql:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/0001_init_db.sql
    ports:
      - 54320:5432
#
#  localstack:
#    image: localstack/localstack
#    ports:
#      - "4566:4566"
#    environment:
#      - SERVICES=s3,sqs,eventbridge
#      - DEFAULT_REGION=us-east-1
#    volumes:
#      - ./localstack:/docker-entrypoint-initaws.d
  
    


