services:
  proxy:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./dev-services/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
  auth:
    build: 
      context: auth
      dockerfile: Dockerfile
    environment:
      - SIGNING_KEY=supersecretkeysupersecretkeysupersecretkey 
      - ISSUER=http://localhost:8080
      - AUDIENCE=http://localhost:8080
      - DATABASE_URL=postgres://root:root@postgresql:5432/user_db
  ingestion:
    build: 
      context: . # Build context is the root of the project because we pull the libs directory
      dockerfile: ingestion/Dockerfile
    environment:
      - DATABASE_URL=postgres://root:root@postgresql:5432/ingestion_db
      - AUTH_SERVICE_URL=http://auth:3000
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ENDPOINT_URL_S3=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=keyid
      - AWS_SECRET_ACCESS_KEY=supersecretkey
      - USE_PATH_STYLE_BUCKETS=true
      - UPLOAD_QUEUE_URL=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/upload-queue
  virus-scan:
    build: 
      context: virus-scan
      dockerfile: Dockerfile
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=keyid
      - AWS_SECRET_ACCESS_KEY=supersecretkey
      - UPLOAD_QUEUE_URL=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/upload-queue
    depends_on:
      - localstack
  postgresql:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/0001_init_db.sql
    ports:
      - 54320:5432

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=keyid 
      - AWS_SECRET_ACCESS_KEY=supersecretkey
      - SERVICES=s3,sqs,eventbridge
    volumes:
      - ./dev-services/localstack/:/etc/localstack/init/ready.d/
  
    


